version: '3.3'
networks:
  jaeger:

services:

    app:
        build: ./
        container_name: otel-collector-demo
        #ports:
        #    - "8080:8080"
        #environment:
            # 外网ip，用于访问jaeger UI
            ##- JAVA_OPTS=-javaagent:opentelemetry-javaagent.jar -Dotel.resource.attributes=service.name=otel-collector-demo -Dotel.traces.exporter=jaeger -Dotel.metrics.exporter=none
        network_mode: host

    jaeger:
        image: jaegertracing/all-in-one:1.29
        #ports:
        #    - 5775:5775/udp
        #    - 6831:6831/udp
        #    - 6832:6832/udp
        #    - 5778:5778
        #    - 16686:16686
        #    - 14250:14250
        #    - 14268:14268
        #    - 14269:14269
        #    - 9411:9411
        network_mode: host


    # Collector
    otel-collector:
      ## 用最新collecotr版本 otel/opentelemetry-collector-contrib:0.74.0
      image: otel/opentelemetry-collector-contrib:0.74.0
      command: ["--config=/etc/otel-collector-config.yaml"]
      ##在rules目录下提供更多Collector 插件使用示例
      volumes:
        - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
      ##ports:
      ##  - "1888:1888"   # pprof extension
      ##  - "8888:8888"   # Prometheus metrics exposed by the collector
      ##  - "8889:8889"   # Prometheus exporter metrics
      ##  - "13133:13133" # health_check extension
      ##  - "4317:4317"        # OTLP gRPC receiver
      ##  - "4318:4318"        # OTLP HTTP receiver
      ##  - "55670:55679" # zpages extension
      network_mode: host

    prometheus:
      container_name: prometheus
      image: prom/prometheus:latest
      volumes:
        - ./prometheus.yaml:/etc/prometheus/prometheus.yml
      #ports:
      #  - "9090:9090"
      #  - "9464:9464"
      network_mode: host