receivers:
  otlp:
    protocols:
      grpc:

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
    const_labels:
      label1: value1
  ##设置exporters上报 collector 控制台信息
  logging:
    loglevel: "debug"

  jaeger:
    endpoint: 127.0.0.1:14250
    tls:
      insecure: true

processors:
  batch:
  tail_sampling:
    ##decision_wait: 10s
    ##num_traces: 100
    ##expected_new_traces_per_sec: 100
    ##定义尾部采样规则，只采集http status 返回非200 的链路信息
    policies:
      [
          {
            name: test-policy-1,
            type: status_code,
            status_code: {status_codes: [ERROR]}
          }
      ]

extensions:
  health_check:
  pprof:
    endpoint: :1888

service:
  extensions: [pprof,health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [tail_sampling]
      exporters: [jaeger,logging]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus,logging]
##设置 Collector log level
  telemetry:
    logs:
      level: "info"