receivers:
  otlp:
    protocols:
      grpc:

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
    const_labels:
      label1: value1
  logging:

  jaeger:
    endpoint: 127.0.0.1:14250
    tls:
      insecure: true

processors:
  batch:
  tail_sampling:
    ##decision_wait: 10s
    ##num_traces: 100
    ##expected_new_traces_per_sec: 100
    policies:
      [
          {
            name: test-policy-5,
            type: status_code,
            status_code: {status_codes: [ERROR]}
          }
      ]

extensions:
  health_check:
    ##endpoint: "127.0.0.1:13134"
    ##check_collector_pipeline:
    ##  enabled: true
    ##  interval: "1m"
    ##  exporter_failure_threshold: 5
  pprof:
    endpoint: :1888


service:
  extensions: [pprof,health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [tail_sampling]
      exporters: [jaeger]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]